### ISSUE TITLE
Method called from Godot causes crash when parameter is null

### ISSUE THREAD

**Issue by Beliar83** [raulsntos/godot-dotnet#15]
### Godot version

4.3-stable

### Godot .NET packages version

1ac3529c5320de4a46787d705e8a6e82b09f00a7

### System information

Windows 11

### .NET information

8.0.202

### Issue description

When godot calls ScriptLanguageExtension._CompleteCode the third parameter can be null, if the edited script is not attached to any node. This causes an exception in native code called from [this](https://github.com/raulsntos/godot-dotnet/blob/1ac3529c5320de4a46787d705e8a6e82b09f00a7/src/Godot.Bindings/NativeInterop/Marshallers/GodotObjectMarshaller.cs#L36), which is called from [this](https://github.com/raulsntos/godot-dotnet/blob/1ac3529c5320de4a46787d705e8a6e82b09f00a7/src/Godot.Bindings/NativeInterop/Marshalling.Ptr.cs#L628),
which is called from "MethodBindInvoker.From.cs", at `global::Godot.NativeInterop.Marshalling.ConvertFromUnmanaged<T2>(args[2])`:

```static void TrampolineWithPtrArgs(global::Godot.GodotObject instance, global::System.Delegate @delegate, void** args, void* outRet)
{
	TResult res = ((global::System.Func<TInstance, T0, T1, T2, TResult>)@delegate)(
		(TInstance)instance,
		global::Godot.NativeInterop.Marshalling.ConvertFromUnmanaged<T0>(args[0]),
		global::Godot.NativeInterop.Marshalling.ConvertFromUnmanaged<T1>(args[1]),
		global::Godot.NativeInterop.Marshalling.ConvertFromUnmanaged<T2>(args[2])
	);
	global::Godot.NativeInterop.Marshalling.WriteUnmanaged<TResult>(outRet, in res);
}
```
There is a null check in GetOrCreateManagedInstance, but it seems that args[2] is not null, for some reason.

The godot call is [here](https://github.com/godotengine/godot/blob/77dcf97d82cbfe4e4615475fa52ca03da645dbd8/editor/plugins/script_text_editor.cpp#L871) and the override for ScriptLanguageExtension is [here](https://github.com/godotengine/godot/blob/77dcf97d82cbfe4e4615475fa52ca03da645dbd8/core/object/script_language_extension.h#L407)

This is as far as I can get with my knowledge of native interop.

### Steps to reproduce

Inherit from class that has a method where a parameter can be null (ScriptLanguageExtension and _CompleteCode, for example)
Perform action in the editor that causes that parameter to be passed as null.

### Minimal reproduction project

-

**Comment by raulsntos** [comment]
The code that calls the virtual method in the engine is implemented like this:

```c++
PtrToArg<m_type1>::EncodeT argval1 = (PtrToArg<m_type1>::EncodeT)arg1;
PtrToArg<m_type2>::EncodeT argval2 = (PtrToArg<m_type2>::EncodeT)arg2;
PtrToArg<m_type3>::EncodeT argval3 = (PtrToArg<m_type3>::EncodeT)arg3;
GDExtensionConstTypePtr argptrs[3] = { &argval1, &argval2, &argval3 };
PtrToArg<m_ret>::EncodeT ret;
if (_get_extension()->get_virtual_call_data && _get_extension()->call_virtual_with_data) {
    _get_extension()->call_virtual_with_data(_get_extension_instance(), &_gdvirtual__complete_code_sn, _gdvirtual__complete_code, reinterpret_cast<GDExtensionConstTypePtr *>(argptrs), &ret);
    r_ret = (m_ret)ret;
} else {
    ((GDExtensionClassCallVirtual)_gdvirtual__complete_code)(_get_extension_instance(), reinterpret_cast<GDExtensionConstTypePtr *>(argptrs), &ret);
    r_ret = (m_ret)ret;
}
```

This is generated using the [`make_virtuals.py`](https://github.com/godotengine/godot/blob/61598c5c88d95b96811d386cb20d714c35f4c6d7/core/object/make_virtuals.py) script. It generates a `gdvirtual.gen.inc` when compiling the engine.

As you can see, it encodes the arguments taking a reference with `&`. This means, for a `Object *` argument it's taking a reference to that pointer. That's why what we receive is not `null` but a pointer to a `null` pointer. Objects are basically encoded as `Object **`.

The code that converts this argument in `godot-cpp` is in [`method_ptrcall.hpp`](https://github.com/godotengine/godot-cpp/blob/d47758910428242169ebe59329b449edf16036e0/include/godot_cpp/core/method_ptrcall.hpp#L170-L192):

```c++
template <typename T>
struct PtrToArg<T *> {
    static_assert(std::is_base_of<Object, T>::value, "Cannot encode non-Object value as an Object");
    _FORCE_INLINE_ static T *convert(const void *p_ptr) {
        return likely(p_ptr) ? reinterpret_cast<T *>(godot::internal::get_object_instance_binding(*reinterpret_cast<GDExtensionObjectPtr *>(const_cast<void *>(p_ptr)))) : nullptr;
    }
    typedef Object *EncodeT;
    _FORCE_INLINE_ static void encode(T *p_var, void *p_ptr) {
        *reinterpret_cast<const void **>(p_ptr) = likely(p_var) ? p_var->_owner : nullptr;
    }
};
```

This is similar to what we do in [`Marshalling.ConvertFromUnmanaged<T>`](https://github.com/raulsntos/godot-dotnet/blob/1ac3529c5320de4a46787d705e8a6e82b09f00a7/src/Godot.Bindings/NativeInterop/Marshalling.Ptr.cs#L606-L629). But as you can see they dereference the pointer before passing it to `get_object_instance_binding` (which is equivalent to `GodotObjectMarshaller.GetOrCreateManagedInstance`). So we should probably do the same.

**Comment by Beliar83** [comment]
@raulsntos It does fix it
